opensearch:
  enabled: true
  clusterName: opensearch
  fullnameOverride: opensearch
  nodeGroup: ""
  imagePullPolicy: Always
  opensearchJavaOpts: "-Xmx1g -Xms1g"
  persistence:
    size: 30Gi
  protocol: http
  config:
    opensearch.yml: |
      plugins.security.disabled: true
  singleNode: true
  resources:
    requests:
      cpu: "100m"
      memory: "256M"
    limits:
      cpu: "2000m"
      memory: "2048M"

airflow:
  enabled: true
  ingress:
    enabled: false
    apiVersion: networking.k8s.io/v1
    web:
      annotations: {}
      labels: {}
      path: ""
      host: ""
      ingressClassName: ""
      tls:
        enabled: false
        secretName: ""
      precedingPaths: []
      succeedingPaths: []
  airflow:
    image:
      repository: docker.getcollate.io/openmetadata/ingestion
      tag: 1.5.6
      pullPolicy: "IfNotPresent"
    executor: "KubernetesExecutor"
    config:
      # This is required for OpenMetadata UI to fetch status of DAGs
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.session,airflow.api.auth.backend.basic_auth"
      # OpenMetadata Airflow Apis Plugin DAGs Configuration
      AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS: "/opt/airflow/dags"
      # OpenMetadata Airflow Secrets Manager Configuration
      AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AWS_REGION: ""
      AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AWS_ACCESS_KEY_ID: ""
      AIRFLOW__OPENMETADATA_SECRETS_MANAGER__AWS_ACCESS_KEY: ""
    users:
    - username: admin
      password: b4Wv2K659XLymdxgJjVrqw
      role: Admin
      email: admin@admin.com
      firstName: admin
      lastName: admin
  externalDatabase:
    type: postgres
    host: openmetadata-dependencies-postgresql
    port: 5432
    database: airflow_db
    user: airflow_user
    passwordSecret: airflow-postgres-secrets
    passwordSecretKey: airflow-postgres-password
  dags:
    persistence:
      enabled: true
      # NOTE: "" means cluster-default
      storageClass: ""
      size: 1Gi
      accessMode: ReadWriteMany
  logs:
    persistence:
      enabled: true
      # empty string means cluster-default
      storageClass: ""
      accessMode: ReadWriteMany
      size: 1Gi

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 15.8.0
  postgresqlPassword: postgres
  initdbScripts:
    my_init.sql: |
      CREATE DATABASE openmetadata_db;
      CREATE DATABASE airflow_db;
      CREATE USER openmetadata_user WITH PASSWORD 'n6NsLT5gduAU3P8aYV42KE';
      CREATE USER airflow_user WITH PASSWORD 'GJ9XkVeYWDzQmxvCcjRadA';
      ALTER DATABASE openmetadata_db OWNER TO openmetadata_user;
      ALTER DATABASE airflow_db OWNER TO airflow_user;
      ALTER USER airflow_user SET search_path = public;
      commit;